const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path'); const http=require('node:http');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'position-plans-')); process.env.POSITIONASSISTANT_DB_PATH=path.join(dir,'db.json'); fs.writeFileSync(process.env.POSITIONASSISTANT_DB_PATH,JSON.stringify({users:[],funds:[],transactions:[],plans:[],quotas:[],fundCatalog:[]})); const {app,validatePlan}=require('../server');
function call(port,method,route,token,body){return new Promise((resolve,reject)=>{const r=http.request({port,method,path:route,headers:{Authorization:token?`Bearer ${token}`:'',...(body?{'Content-Type':'application/json'}:{})}},res=>{let t='';res.on('data',c=>t+=c);res.on('end',()=>resolve({status:res.statusCode,body:t?(t.trim().startsWith('{')||t.trim().startsWith('[')?JSON.parse(t):t):null}))});r.on('error',reject);if(body)r.write(JSON.stringify(body));r.end()})}
test('定投计划字段校验与账号隔离',async t=>{const server=app.listen(0);t.after(()=>{server.close()});const port=server.address().port; const reg=await call(port,'POST','/api/auth/register',null,{email:'p@example.com',password:'password-p'});assert.equal(reg.status,201);const login=await call(port,'POST','/api/auth/login',null,{email:'p@example.com',password:'password-p'});const token=login.body.token;assert.throws(()=>validatePlan({fundCode:'x'}),/基金代码/);assert.equal((await call(port,'POST','/api/plans',token,{fundCode:'160213',fundName:'测试基金',mode:'amount',amount:500,cycle:'monthly',startDate:'2026-10-01',executionDay:15})).status,201);const list=await call(port,'GET','/api/plans',token);assert.equal(list.body.length,1);assert.equal(list.body[0].amount,500);const id=list.body[0].id;const edited=await call(port,'PUT','/api/plans/'+id,token,{amount:650,executionDay:20});assert.equal(edited.status,200);assert.equal(edited.body.amount,650);assert.equal((await call(port,'POST','/api/plans/'+id+'/pause',token)).body.enabled,false);assert.equal((await call(port,'POST','/api/plans/'+id+'/enable',token)).body.enabled,true);assert.equal((await call(port,'PATCH','/api/plans/'+id+'/status',token,{enabled:'yes'})).status,400);assert.equal((await call(port,'POST','/api/plans/nope/pause',token)).status,404);assert.equal((await call(port,'POST','/api/plans',token,{fundCode:'160213',mode:'shares',shares:0,cycle:'weekly',startDate:'2026-10-01',executionDay:1})).status,400);assert.equal((await call(port,'POST','/api/plans',token,{fundCode:'160213',mode:'amount',amount:100,cycle:'weekly',startDate:'2026-10-01',executionDay:8})).status,400);assert.equal((await call(port,'POST','/api/plans',null,{fundCode:'160213',mode:'amount',amount:100,cycle:'weekly',startDate:'2026-10-01',executionDay:1})).status,401)});


test('定投待记账生成幂等',async t=>{const server=app.listen(0);t.after(()=>{server.close();fs.rmSync(dir,{recursive:true,force:true})});const port=server.address().port;const login=await call(port,'POST','/api/auth/login',null,{email:'p@example.com',password:'password-p'});const token=login.body.token;const list=await call(port,'GET','/api/plans',token);const id=list.body[0].id;const first=await call(port,'POST',`/api/plans/${id}/entries/generate`,token,{scheduledDate:'2026-10-20'});assert.equal(first.status,201);assert.equal(first.body.status,'pending');const second=await call(port,'POST',`/api/plans/${id}/entries/generate`,token,{scheduledDate:'2026-10-20'});assert.equal(second.status,200);assert.equal(second.body.id,first.body.id);assert.equal((await call(port,'GET',`/api/plans/${id}/entries`,token)).body.length,1);assert.equal((await call(port,'POST',`/api/plans/${id}/entries/generate`,token,{scheduledDate:'2026-10-21'})).status,400)});
test('定投一期可补录并修改待确认日期',async t=>{const server=app.listen(0);t.after(()=>{server.close();fs.rmSync(dir,{recursive:true,force:true})});const port=server.address().port;await call(port,'POST','/api/auth/register',null,{email:'supplement@example.com',password:'password-p'});const login=await call(port,'POST','/api/auth/login',null,{email:'supplement@example.com',password:'password-p'});const token=login.body.token;const created=await call(port,'POST','/api/plans',token,{fundCode:'160213',fundName:'测试基金',mode:'amount',amount:500,cycle:'monthly',startDate:'2026-10-01',executionDay:20});const id=created.body.id;await call(port,'POST',`/api/plans/${id}/pause`,token);const added=await call(port,'POST',`/api/plans/${id}/entries/supplement`,token,{scheduledDate:'2026-10-20'});assert.equal(added.status,201);const changed=await call(port,'PUT',`/api/plans/${id}/entries/${added.body.id}`,token,{scheduledDate:'2026-11-20',note:'补录'});assert.equal(changed.status,200);assert.equal(changed.body.scheduledDate,'2026-11-20');assert.equal(changed.body.note,'补录');assert.equal((await call(port,'POST',`/api/plans/${id}/entries/supplement`,token,{scheduledDate:'2026-11-20'})).status,200);assert.equal((await call(port,'PUT',`/api/plans/${id}/entries/${added.body.id}`,token,{scheduledDate:'2026-11-21'})).status,400)});

test('定投一期可跳过且幂等并阻止确认',async t=>{const server=app.listen(0);t.after(()=>{server.close();fs.rmSync(dir,{recursive:true,force:true})});const port=server.address().port;await call(port,'POST','/api/auth/register',null,{email:'skip@example.com',password:'password-p'});const login=await call(port,'POST','/api/auth/login',null,{email:'skip@example.com',password:'password-p'});const token=login.body.token;const plan=await call(port,'POST','/api/plans',token,{fundCode:'160213',fundName:'测试基金',mode:'amount',amount:500,cycle:'monthly',startDate:'2026-10-01',executionDay:20});const id=plan.body.id;const made=await call(port,'POST',`/api/plans/${id}/entries/generate`,token,{scheduledDate:'2026-10-20'});const skipped=await call(port,'POST',`/api/plans/${id}/entries/${made.body.id}/skip`,token,{note:'本期暂停'});assert.equal(skipped.status,200);assert.equal(skipped.body.status,'skipped');assert.equal(skipped.body.skipNote,'本期暂停');assert.ok(skipped.body.skippedAt);const again=await call(port,'POST',`/api/plans/${id}/entries/${made.body.id}/skip`,token);assert.equal(again.status,200);assert.equal(again.body.id,made.body.id);assert.equal((await call(port,'POST',`/api/plans/${id}/entries/${made.body.id}/confirm`,token)).status,409);assert.equal((await call(port,'POST',`/api/plans/${id}/entries/${made.body.id}/skip`,null)).status,401)});



